### ISSUE TITLE
should we keep 2.12 ?

### ISSUE THREAD

**Issue by hamnis** [circe/circe-refined#1]
Are there any users on the current circe-refined that still uses 2.12 ?

@zarthross do we have any download stats that may answer that?

**Comment by zarthross** [comment]
These are just the JVM stats.  I'm included 2.10 and 2.11 for perspective
Scala 2.10:
![image](https://github.com/user-attachments/assets/f4144461-b4df-4933-ab8d-8bc8f2c50b1d)
Scala 2.11
![image](https://github.com/user-attachments/assets/141c32d2-d50a-4aed-8882-82091316463d)
Scala 2.12
![image](https://github.com/user-attachments/assets/bb8db589-4f59-43a4-9935-18c870440192)
Scala 2.13
![image](https://github.com/user-attachments/assets/0ac9def2-1c59-41c0-9579-52f970d45574)
Scala 3
![image](https://github.com/user-attachments/assets/10afd89d-fcef-4fb8-ae96-78a6dd3887d7)


Looks to me like we have only slightly fewer 2.12 users than Scala 3 users 😆.  Not sure how much of a burden it is to support to 2.12, IMHO, if its easy we do it, if its hard, we drop it.  That has been my stance on circe-core for a while, so far we haven't had any serious issues needed us to drop 2.12.

**Comment by hamnis** [comment]
Allrighy then. re-added 2.12 support.
